version: '3.8'

services:
  database:
    container_name: database_punk_api
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: punk_api_db
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "4306:3306"
    volumes:
      - db:/var/lib/mysql

  test_database:
    container_name: database_punk_api_test
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: punk_api_db_test
      MYSQL_USER: symfony_test
      MYSQL_PASSWORD: symfony
    ports:
      - "4307:3306"
    volumes:
      - db_test:/var/lib/mysql_test

  php:
    container_name: php_punk_api
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/punk_api
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    depends_on:
      - database

  nginx:
    container_name: nginx_punk_api
    image: nginx
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/punk_api
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
  
  redis:
    container_name: redis_punk_api
    image: redis:latest
    ports:
      - '6379:6379'
    volumes: 
      - ./redis:/data

volumes:
  db:
  db_test:
